# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Ashton Shears
tagline:          ''
description:      'My personal website showing some of what I find interesting.'
url:              http://hyde.getpoole.com
baseurl:          /


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
